spring:
  application:
    name: ollama
  ai:
    ollama:
      chat:
#        model: deepseek-r1:7b
        model: llama3.1

logging:
  level:
    # Spring AI core logging
    org.springframework.ai: DEBUG

    # Ollama-specific logging
    org.springframework.ai.ollama: DEBUG
    ai.ollama.chat: DEBUG

    # HTTP client logging for request/response details
    org.springframework.web.client: DEBUG
    org.springframework.http.client: TRACE
    org.springframework.web.reactive.function.client: DEBUG